(function(a){a.fn.bannerShow=function(f){f=jQuery.extend({wraper:"bgimg",autotime:6E3,isAuto:true,ind:0},f||{});return this.each(function(){function h(c){a("#bgarea").find("li").removeClass("cur").hide();c=a("#bgarea").find("li").eq(c);a("#"+f.wraper).removeClass().addClass(c.attr("id"));c.show();var d=c.find("img"),e=d.attr("src");if(e.indexOf("-s-")!==-1)c=new Image,c.onload=function(){d.attr("src",e.replace("-s",""))},c.src=e.replace("-s","")}var c=0,e=a("#bnav"),g=a("li",e);a(this).hover(function(){f.isAuto=
false},function(){f.isAuto=true});h(0);g.each(function(e,d){a(d).mouseover(function(){c=e;g.removeClass().eq(c).addClass("current");h(c)})});setInterval(function(){if(!f.isAuto)return false;g.each(function(e,d){a(d).hasClass("current")&&(c=e);h(c)});c==g.size()-1?c=0:c+=1;h(c);g.removeClass().eq(c).addClass("current")},f.autotime)})}})(jQuery);
$(function(){$("#copytime").html((new Date).getFullYear());$("#bgimg").bannerShow();setTimeout(scrollTo,0,0,1);$(window).height();$(".ipage").size();var a=0,f=null,h=function(){var b=document.createElement("div"),c="Khtml Ms O Moz Webkit".split(" ");return function(a){if(a in b.style)return true;for(var a=a.replace(/^[a-z]/,function(b){return b.toUpperCase()}),d=c.length;d--;)if(c[d]+a in b.style)return true;return false}}(),c=function(){};typeof pgvMain!="function"&&$.getScript("http://pingjs.qq.com/tcss.ping.js?v=1",
function(){typeof pgvMain=="function"&&pgvMain();c=pgvSendClick;$(".forTcss").click(function(){var b=$(this).attr("name");window.setTimeout(function(){c({hottag:b})},500)})});if(h("transform")&&h("transition")&&navigator.userAgent.indexOf("QQBrowser")===-1){$("body").addClass("haswheel");c&&window.setTimeout(function(){c({hottag:"pcqq.w3cbrowser"})},600);$(window).mousewheel(function(b,c,a,d){f&&window.clearTimeout(f);f=window.setTimeout(function(){d<0?i(1):i(-1)},300)});$(".page5").height();var e=
{},g=function(){var b=[0],c=0,a=$(window).height(),a=a>720?a:720;$(".ipage").each(function(b,a){c+=$(a).height()});c+=50;for(var d=c%a,f=Math.floor(c/a),h=d===0?f:Math.ceil(c/a),g=0;g<f-1;)b.push(a+b[g]),g++;d&&b.push(d+b[f-1]);e.arr=b;e.inds=h;return e};g();$(window).resize(function(){g();i(0)});$(window).keydown(function(b){b.preventDefault();switch(b.keyCode||b.which||b.charCode){case 38:i(-1);break;case 40:i(1)}});var j=$("#sidenav").find("li");j.click(function(){var b=$(this).attr("tabid");i(b-
a+1)});var d=0,i=function(b){a+=b;d+=b;b=e.inds-1;if(a<0||a===0)a=0;else if(a===b||a>b)a=b;if(d<0||d===0)d=0;else if(d===b||d>b)d=b;a>0?$("#navfix").show().addClass("moveInTop"):$("#navfix").removeClass("moveInTop").hide();a>0&&a<13?($("#sidenav").fadeIn(),j.removeClass(),j.eq(a-1).addClass("showed")):$("#sidenav").hide();$("body").attr("id","page"+a);$("#poswrap").css({"-webkit-transform":"translate(0px, -"+e.arr[d]+"px)","-moz-transform":"translate(0px, -"+e.arr[d]+"px)","-o-transform":"translate(0px, -"+
e.arr[d]+"px)","-ms-transform":"translate(0px, -"+e.arr[d]+"px)",transform:"translate(0px, -"+e.arr[d]+"px)"})}}h=new Date;$("#copyYear").text(h.getFullYear());window.online_resp=function(b){b&&b.c&&($("#cur_online").text(b.c.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g,"$1,")),$("#max_online").text(b.h.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g,"$1,")))};$.getJSON("http://mma.qq.com/cgi-bin/im/online&callback=?",function(){});swfobject.embedSWF("http://im.qq.com/online/flash/flash20140304.swf",
"flashBox","910","700","9.0.0","expressInstall.swf");$("#viewOnline").click(function(b){b.preventDefault();$("#flashDiv").show();$("#overlay").show();$("#overlay").css({height:$(document).height()});c({hottag:"pcqq.openflash"})});$("#flashClose").click(function(){$("#flashDiv").hide();$("#overlay").hide()});$("#flashZone").click(function(){var b=($(window).width()-615)/2,a=($(window).height()-713)/2;window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=http%3A%2F%2Fim.qq.com%2F&showcount=1&desc=%E4%BA%BF%E4%B8%87%E4%B8%AA%E9%97%AA%E8%80%80%E6%98%9F%E5%85%89%E8%83%8C%E5%90%8E%EF%BC%8C%E6%98%AF%E6%9C%8B%E5%8F%8B%EF%BC%8C%E6%98%AF%E5%AE%B6%E4%BA%BA%EF%BC%8C%E6%98%AF%E7%88%B1%E4%BA%BA%E2%80%A6%E2%80%A6%E7%99%BB%E5%BD%95QQ%EF%BC%8C%E4%B8%BA%E4%BB%96%EF%BC%88%E5%A5%B9%EF%BC%89%E7%82%B9%E4%BA%AE%E4%BD%A0%E7%9A%84%E9%82%A3%E9%A2%97%E6%98%9F%E3%80%82&summary=&title=&site=IM%20QQ%20-%20QQ%E5%AE%98%E6%96%B9%E7%BD%91%E7%AB%99&pics=http%3A%2F%2Fim-img.qq.com%2Fhome%2Fimg%2Fq2013%2Fyun.png&style=203&width=98&height=22&otype=share",
"_blank","toolbar=yes, location=yes, directories=no, status=no, menubar=yes, scrollbars=yes, resizable=no, copyhistory=yes, width=615, height=363, left="+b+", top="+a);c({hottag:"pcqq.sharetozone"})});$("#flashWeibo").click(function(){window.open("http://share.v.t.qq.com/index.php?c=share&a=index&url=http%3A%2F%2Fim.qq.com%2F&title=%E4%BA%BF%E4%B8%87%E4%B8%AA%E9%97%AA%E8%80%80%E6%98%9F%E5%85%89%E8%83%8C%E5%90%8E%EF%BC%8C%E6%98%AF%E6%9C%8B%E5%8F%8B%EF%BC%8C%E6%98%AF%E5%AE%B6%E4%BA%BA%EF%BC%8C%E6%98%AF%E7%88%B1%E4%BA%BA%E2%80%A6%E2%80%A6%E7%99%BB%E5%BD%95QQ%EF%BC%8C%E4%B8%BA%E4%BB%96%EF%BC%88%E5%A5%B9%EF%BC%89%E7%82%B9%E4%BA%AE%E4%BD%A0%E7%9A%84%E9%82%A3%E9%A2%97%E6%98%9F%E3%80%82&pic=http%3A%2F%2Fim-img.qq.com%2Fhome%2Fimg%2Fq2013%2Fyun.png&appkey=",
"_blank","toolbar=yes, location=yes, directories=no, status=no, menubar=yes, scrollbars=yes, resizable=no, copyhistory=yes, width=615, height=363");c({hottag:"pcqq.sharetoweibo"})})});
